# Bike Sharing Demand Kaggle project

W207 Final Project

Chris Murray, Rahul Ragunathan, Rajagopalan Mahadevan

https://www.kaggle.com/c/bike-sharing-demand/


In [12]:
# This tells matplotlib not to try opening a new window for each plot.
%matplotlib inline

# General libraries.
import numpy as np
import matplotlib.pyplot as plt

# SK-learn libraries for learning.
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.grid_search import GridSearchCV

# SK-learn libraries for evaluation.
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report

Data files have been downloaded into `data/` .

Fields are described here: https://www.kaggle.com/c/bike-sharing-demand/data

The last field **count** is what we are trying to predict.

In [95]:
ff = "data/train.csv"
f = open(ff)
column_names = f.readline()

print column_names

# really simple function that returns the hour as an integer
getHour = lambda x: int(x[11:13])

# convert string to float and round to integer
getRounded = lambda x: int(round(float(x)))

# read data file and convert everything to integers
data = np.genfromtxt(f, delimiter=",", dtype=int, converters=
                {0: getHour, 5: getRounded, 6: getRounded, 8: getRounded})

print data[0:5]

# extract the last column (count) into y and all the features into X
y, X = data[:, :1], data[:, 1:]

print X.shape
print

ff_test = "data/test.csv"
f_test = open(ff_test)
column_names_test = f_test.readline()

print column_names_test

data_test = np.genfromtxt(f_test, delimiter=",", dtype=int, converters=
                {0: getHour, 5: getRounded, 6: getRounded, 8: getRounded})

print data_test[0:5]

# note there are no labels here!
X_test = data_test

print X_test.shape

datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count

[[ 0  1  0  0  1 10 14 81  0  3 13 16]
 [ 1  1  0  0  1  9 14 80  0  8 32 40]
 [ 2  1  0  0  1  9 14 80  0  5 27 32]
 [ 3  1  0  0  1 10 14 75  0  3 10 13]
 [ 4  1  0  0  1 10 14 75  0  0  1  1]]
(10886, 11)

datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed

[[ 0  1  0  1  1 11 11 56 26]
 [ 1  1  0  1  1 11 14 56  0]
 [ 2  1  0  1  1 11 14 56  0]
 [ 3  1  0  1  1 11 13 56 11]
 [ 4  1  0  1  1 11 13 56 11]]
(6493, 9)


NOTE: this is as far as I've gotten!  Below is from the Kaggle demo notebook from Dan.  -Chris

Now, we train a model, let's just do KNN, no time to think!

In [ ]:
# to make this faster, just use the first 1000
y_train, X_train = y[:1000], X[:1000, :]

kn = KNeighborsClassifier(n_neighbors=1)

kn.fit(X_train, y_train)

# here's what we need to send back to Kaggle
preds = kn.predict(X_test)

Now we need to save the output to a textfile, and upload the results to kaggle!

Read the data page to make you submission the right format:

https://www.kaggle.com/c/digit-recognizer/data

In [7]:
test_lab_f = open("/Users/dancsi/Downloads/test_labeled.csv", "w") # you will need to edit this directory

idx = 0
                 
for pp in preds:
    idx += 1
    test_lab_f.write(str(int(pp)))
    if idx < 28000:
        test_lab_f.write("\n") # the if statement ensures that we don't end with a newline!
    
print idx

test_lab_f.close()

28000


Well, that didn't work. I guess that is becuase the submission page lied. Here's the correct format (you can deduce this from the error message):

In [8]:
test_lab_f = open("/Users/dancsi/Downloads/test_labeled.csv", "w") # you will need to edit this directory

test_lab_f.write("ImageId,Label")

idx = 0
                 
for pp in preds:
    idx += 1
    test_lab_f.write("\n")
    test_lab_f.write(str(idx) + "," + str(int(pp)))
   

test_lab_f.close()